version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: contacts-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: contacts
    ports:
      - "5430:5432"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
    restart: unless-stopped

  app:
    container_name: contacts
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5430/contacts
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=12345
      - SERVER_PORT=8081
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - postgres
